#!/bin/sh

# test success
# merge two passwd files
# expect success
# run again on merged result
# second pass should be same as first

source test_lib

if [ $# != 2 ]; then
	echo $0: $#
	usage bin data_dir
fi

bin="$1"
data_dir="$2"
result=$results_dir/test_fail

test_begin

expect_success mkdir -p $result
expect_failure $bin $data_dir/{l,r}{passwd,shadow} $result/m{passwd,shadow}

test_passed
